---
- name: Look up existing account
  include_tasks: account_lookup.yml

- name: Create account
  uri:
    url: "https://{{ cyberark_subdomain }}.privilegecloud.cyberark.cloud/passwordvault/api/Accounts"
    method: POST
    headers:
      Authorization: "Bearer {{ cyberark_token }}"
    body_format: json
    body:
      name: "{{ cyberark_account_name }}"
      address: "{{ cyberark_account_address }}"
      userName: "{{ cyberark_account_username }}"
      platformId: "{{ cyberark_account_platform_id }}"
      safeName: "{{ cyberark_account_safe }}"
      secretType: "{{ cyberark_account_secret_type }}"
      secret: "{{ cyberark_account_secret }}"
      platformAccountProperties: "{{ cyberark_account_platform_properties }}"
      secretManagement:
        automaticManagementEnabled: "{{ cyberark_account_automatic_management_enabled }}"
        manualManagementReason: "{{ cyberark_account_manual_management_reason }}"
    status_code: [201]
    timeout: 30
    validate_certs: "{{ cyberark_validate_certs }}"
  register: _cyberark_account_create
  when: not cyberark_account_exists
  run_once: true
  delegate_to: localhost

- name: Update account
  uri:
    url: "https://{{ cyberark_subdomain }}.privilegecloud.cyberark.cloud/passwordvault/api/Accounts/{{ cyberark_account_id }}"
    method: PATCH
    headers:
      Authorization: "Bearer {{ cyberark_token }}"
    body_format: json
    body:
      - op: replace
        path: /name
        value: "{{ cyberark_account_name }}"
      - op: replace
        path: /address
        value: "{{ cyberark_account_address }}"
      - op: replace
        path: /userName
        value: "{{ cyberark_account_username }}"
      - op: replace
        path: /platformId
        value: "{{ cyberark_account_platform_id }}"
      - op: replace
        path: /secretManagement/automaticManagementEnabled
        value: "{{ cyberark_account_automatic_management_enabled }}"
      - op: replace
        path: /secretManagement/manualManagementReason
        value: "{{ cyberark_account_manual_management_reason }}"
    status_code: [200]
    timeout: 30
    validate_certs: "{{ cyberark_validate_certs }}"
  register: _cyberark_account_update
  when: cyberark_account_exists
  run_once: true
  delegate_to: localhost

- name: Expose created account as fact
  set_fact:
    cyberark_account_id: "{{ _cyberark_account_create.json.id }}"
    cyberark_account_detail: "{{ _cyberark_account_create.json }}"
  when: not cyberark_account_exists
  run_once: true
  delegate_to: localhost

- name: Expose updated account as fact
  set_fact:
    cyberark_account_detail: "{{ _cyberark_account_update.json }}"
  when: cyberark_account_exists
  run_once: true
  delegate_to: localhost

- name: Update account secret
  include_tasks: account_secret.yml
  when:
    - cyberark_account_secret | trim | length > 0
    - cyberark_account_secret_update or not cyberark_account_exists
